/*
** Copyright 2013 Double Precision, Inc.
** See COPYING for distribution information.
*/

#ifndef x_sql_dbi_flavorobj_H
#define x_sql_dbi_flavorobj_H

#include <x/obj.H>
#include <x/sql/dbi/flavorfwd.H>

namespace LIBCXX_NAMESPACE {
	namespace sql {
		namespace dbi {
#if 0
		};
	};
};
#endif

//! Select DBI SQL flavor

class LIBCXX_HIDDEN flavorObj : virtual public obj {

public:
	//! Constructor
	flavorObj();

	//! Destructor
	~flavorObj() noexcept;

};

#if 0
{
	{
		{
#endif
		};
	};
};
#endif
